# @generated by usage-cli from cc-journal.usage.kdl
_cc_journal() {
    if ! type -p usage &> /dev/null; then
        echo >&2
        echo "Error: usage CLI not found. This is required for completions to work in cc-journal." >&2
        echo "See https://usage.jdx.dev for more information." >&2
        return 1
    fi

	local cur prev words cword was_split comp_args
    _comp_initialize -n : -- "$@" || return
    local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_cc_journal.spec"
    cat >| "$spec_file" <<'__USAGE_EOF__'
name cc-journal
bin cc-journal
about "Capture, summarize, and visualize Claude Code sessions as a developer journal"
min_usage_version "1.3"
cmd serve help="Start dev server with live reload (send SIGHUP to reload config)" {
    flag --port help="Port to listen on" default="8000" {
        arg <PORT>
    }
    flag --templates help="Directory with custom HTML templates" {
        arg <DIR>
    }
}
cmd build help="Generate static HTML site" {
    flag --out help="Output directory" default=public {
        arg <DIR>
    }
    flag --templates help="Directory with custom HTML templates" {
        arg <DIR>
    }
}
cmd standup help="Print daily standup report" {
    flag --copy help="Copy output to clipboard"
    flag --slack help="Send to Slack (optional channel override)" {
        arg "[CHANNEL]" required=#false
    }
    arg "[DATE]" help="Target date (YYYY-MM-DD, default: today)" required=#false
}
cmd weekly help="Print weekly status report by project" {
    flag --end help="Week end date (YYYY-MM-DD)" {
        arg <END>
    }
    flag --copy help="Copy output to clipboard"
    flag --slack help="Send to Slack (optional channel override)" {
        arg "[CHANNEL]" required=#false
    }
    arg "[START]" help="Week start date (YYYY-MM-DD, default: this Monday)" required=#false
}
cmd hook help="SessionEnd hook handler (reads JSON from stdin)"
cmd summarize help="Summarize a session and write to journal" {
    flag --session help="Session ID (alternative to positional arg)" {
        arg <SESSION_ID>
    }
    flag --force help="Re-summarize even if already journaled"
    arg "[SESSION_ID]" help="Session ID to summarize" required=#false
}
cmd backfill help="Retroactively summarize recent sessions" {
    flag --since help="How far back to look (e.g. 1d, 2h, 30m)" default="3d" {
        arg <DURATION>
    }
    flag --rolling help="Use rolling duration instead of aligned (days=midnight, hours=top-of-hour)"
    flag --dry-run help="Show what would be summarized without writing"
    flag --force help="Re-summarize sessions even if already journaled"
}
cmd today help="Print today's journal entries"
cmd show help="Print a specific date's journal entries" {
    arg <DATE> help="Date to show (YYYY-MM-DD)"
}
cmd list help="List all journal files"
cmd week help="Print this week's entries or generate rollup" {
    flag --date help="Date within the target week (alternative to positional arg)" {
        arg <DATE>
    }
    flag --rollup help="Generate AI-powered weekly rollup instead of listing entries"
    arg "[DATE]" help="Date within the target week (YYYY-MM-DD)" required=#false
}
cmd rollup help="Generate AI-powered weekly rollup" {
    arg "[DATE]" help="Date within the target week (YYYY-MM-DD)" required=#false
}
cmd prune help="Remove failed summary entries from journal" {
    flag --dry-run help="Show what would be removed without deleting"
}
cmd remove help="Delete a journal entry and deny future backfills for this session" {
    arg <SESSION_ID> help="Session ID to remove"
}
cmd init help="Export default templates, prompts, and Claude Code commands" {
    flag --templates help="Export HTML templates only"
    flag --prompts help="Export prompt templates only"
    flag --commands help="Install Claude Code slash commands (e.g. /summarize)"
    flag --all help="Export templates, prompts, and commands"
    flag --force help="Overwrite existing files"
    flag --stdout help="Print to stdout instead of writing files"
}
cmd search help="Search journal entries by text" {
    flag --project help="Filter results to a specific project" {
        arg <PROJECT>
    }
    flag --limit help="Maximum number of results" default="20" {
        arg <N>
    }
    arg <QUERY>… help="Search query (matches summary, project, branch)" var=#true
}
cmd version help="Print version information"
__USAGE_EOF__
    # shellcheck disable=SC2207
	_comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
	_comp_ltrim_colon_completions "$cur"
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        unset COMPREPLY
    fi
    return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _cc_journal cc-journal
else
    shopt -u hostcomplete && complete -o nospace -o bashdefault -F _cc_journal cc-journal
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
