# @generated by usage-cli from cc-journal.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in cc-journal." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_cc_journal 'name cc-journal
bin cc-journal
about "Capture, summarize, and visualize Claude Code sessions as a developer journal"
min_usage_version "1.3"
cmd serve help="Start dev server with live reload (send SIGHUP to reload config)" {
    flag --port help="Port to listen on" default="8000" {
        arg <PORT>
    }
    flag --templates help="Directory with custom HTML templates" {
        arg <DIR>
    }
}
cmd build help="Generate static HTML site" {
    flag --out help="Output directory" default=public {
        arg <DIR>
    }
    flag --templates help="Directory with custom HTML templates" {
        arg <DIR>
    }
}
cmd standup help="Print daily standup report" {
    flag --copy help="Copy output to clipboard"
    flag --slack help="Send to Slack (optional channel override)" {
        arg "[CHANNEL]" required=#false
    }
    arg "[DATE]" help="Target date (YYYY-MM-DD, default: today)" required=#false
}
cmd weekly help="Print weekly status report by project" {
    flag --end help="Week end date (YYYY-MM-DD)" {
        arg <END>
    }
    flag --copy help="Copy output to clipboard"
    flag --slack help="Send to Slack (optional channel override)" {
        arg "[CHANNEL]" required=#false
    }
    arg "[START]" help="Week start date (YYYY-MM-DD, default: this Monday)" required=#false
}
cmd hook help="SessionEnd hook handler (reads JSON from stdin)"
cmd summarize help="Summarize a session and write to journal" {
    flag --session help="Session ID (alternative to positional arg)" {
        arg <SESSION_ID>
    }
    flag --force help="Re-summarize even if already journaled"
    arg "[SESSION_ID]" help="Session ID to summarize" required=#false
}
cmd backfill help="Retroactively summarize recent sessions" {
    flag --days help="Number of days to look back" default="30" {
        arg <DAYS>
    }
    flag --dry-run help="Show what would be summarized without writing"
    flag --force help="Re-summarize sessions even if already journaled"
}
cmd today help="Print today\'s journal entries"
cmd show help="Print a specific date\'s journal entries" {
    arg <DATE> help="Date to show (YYYY-MM-DD)"
}
cmd list help="List all journal files"
cmd week help="Print this week\'s entries or generate rollup" {
    flag --date help="Date within the target week (alternative to positional arg)" {
        arg <DATE>
    }
    flag --rollup help="Generate AI-powered weekly rollup instead of listing entries"
    arg "[DATE]" help="Date within the target week (YYYY-MM-DD)" required=#false
}
cmd rollup help="Generate AI-powered weekly rollup" {
    arg "[DATE]" help="Date within the target week (YYYY-MM-DD)" required=#false
}
cmd prune help="Remove failed summary entries from journal" {
    flag --dry-run help="Show what would be removed without deleting"
}
cmd remove help="Delete a journal entry and deny future backfills for this session" {
    arg <SESSION_ID> help="Session ID to remove"
}
cmd init help="Export default templates, prompts, and Claude Code commands" {
    flag --templates help="Export HTML templates only"
    flag --prompts help="Export prompt templates only"
    flag --commands help="Install Claude Code slash commands (e.g. /summarize)"
    flag --all help="Export templates, prompts, and commands"
    flag --force help="Overwrite existing files"
    flag --stdout help="Print to stdout instead of writing files"
}
cmd search help="Search journal entries by text" {
    flag --project help="Filter results to a specific project" {
        arg <PROJECT>
    }
    flag --limit help="Maximum number of results" default="20" {
        arg <N>
    }
    arg <QUERY>… help="Search query (matches summary, project, branch)" var=#true
}
cmd version help="Print version information"
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_cc_journal.spec"
echo $_usage_spec_cc_journal > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc cc-journal -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc cc-journal -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
